### ISSUE TITLE
Remove handlebar dependency

### ISSUE THREAD

**Issue by arvind0598** [arvind0598/nomoogle#2]
The handlebar file is currently not minified, and in the repo.
The PR to fix this issue should remove the dependency entirely, or at least update the file with a minified version.

**Comment by zahrafalah** [comment]
Hi I am interensted in this

**Comment by arvind0598** [comment]
I'm nearly done with this issue, so I'll be closing it out soon.

**Comment by arvind0598** [comment]
> Hi I am interensted in this 
> 
> 

I'm nearly done with this issue so I'll be closing it out soon.

**Comment by arvind0598** [comment]
Fixed in #10
